"""add app permissions to users

Revision ID: 20250117_000006
Revises: 20250117_000005
Create Date: 2025-01-17 00:00:06.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20250117_000006'
down_revision = '20250117_000005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('app_permissions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'app_permissions')
    # ### end Alembic commands ###
