"""add_file_storage_tables

Revision ID: 8bf0dbb9fba9
Revises: 5553f8745c6e
Create Date: 2025-09-21 19:23:10.515694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bf0dbb9fba9'
down_revision = '5553f8745c6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
