"""add_description_to_documents

Revision ID: 9a06b0cb880a
Revises: ac9e4b3dcffc
Create Date: 2025-10-16 17:26:22.681359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a06b0cb880a'
down_revision = 'ac9e4b3dcffc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'description')
    # ### end Alembic commands ###
