"""add_fiscal_year_to_documents

Revision ID: ac9e4b3dcffc
Revises: 7ecb63029764
Create Date: 2025-10-15 11:22:53.762056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac9e4b3dcffc'
down_revision = '7ecb63029764'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add fiscal_year_id column if it doesn't exist
    try:
        op.add_column('documents', sa.Column('fiscal_year_id', sa.Integer(), nullable=True))
    except Exception:
        # Column might already exist, continue
        pass
    # Create index and foreign key for fiscal_year_id
    op.create_index(op.f('ix_documents_fiscal_year_id'), 'documents', ['fiscal_year_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'fiscal_years', ['fiscal_year_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only remove fiscal_year_id from documents table
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_fiscal_year_id'), table_name='documents')
    op.drop_column('documents', 'fiscal_year_id')
    # ### end Alembic commands ###
