"""sync person_type enum values_callable to persian

Revision ID: d3e84892c1c2
Revises: 20250927_000020_add_share_count_and_shareholder_type
Create Date: 2025-09-27 19:18:06.253391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import text
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = 'd3e84892c1c2'
down_revision = '20250927_000020_add_share_count_and_shareholder_type'
branch_labels = None
depends_on = None


def _table_exists(conn, name: str) -> bool:
    res = conn.execute(text(
        "SELECT COUNT(*) FROM information_schema.tables WHERE table_name=:t"
    ), {"t": name})
    return (res.scalar() or 0) > 0


def _column_exists(conn, table: str, col: str) -> bool:
    res = conn.execute(text(
        "SELECT COUNT(*) FROM information_schema.columns WHERE table_name=:t AND column_name=:c"
    ), {"t": table, "c": col})
    return (res.scalar() or 0) > 0


def upgrade() -> None:
    # ### commands auto generated by Alembic - guarded for idempotency ###
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if 'storage_configs' not in existing_tables:
        op.create_table('storage_configs',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('storage_type', sa.String(length=20), nullable=False),
        sa.Column('is_default', sa.Boolean(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('config_data', sa.JSON(), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if 'file_storage' not in existing_tables:
        op.create_table('file_storage',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('original_name', sa.String(length=255), nullable=False),
        sa.Column('stored_name', sa.String(length=255), nullable=False),
        sa.Column('file_path', sa.String(length=500), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('mime_type', sa.String(length=100), nullable=False),
        sa.Column('storage_type', sa.String(length=20), nullable=False),
        sa.Column('storage_config_id', sa.String(length=36), nullable=True),
        sa.Column('uploaded_by', sa.Integer(), nullable=False),
        sa.Column('module_context', sa.String(length=50), nullable=False),
        sa.Column('context_id', sa.String(length=36), nullable=True),
        sa.Column('developer_data', sa.JSON(), nullable=True),
        sa.Column('checksum', sa.String(length=64), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_temporary', sa.Boolean(), nullable=False),
        sa.Column('is_verified', sa.Boolean(), nullable=False),
        sa.Column('verification_token', sa.String(length=100), nullable=True),
        sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['storage_config_id'], ['storage_configs.id'], ),
        sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    if 'file_verifications' not in existing_tables:
        op.create_table('file_verifications',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('file_id', sa.String(length=36), nullable=False),
        sa.Column('module_name', sa.String(length=50), nullable=False),
        sa.Column('verification_token', sa.String(length=100), nullable=False),
        sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('verified_by', sa.Integer(), nullable=True),
        sa.Column('verification_data', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['file_id'], ['file_storage.id'], ),
        sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    # Drop index if exists
    try:
        bind = op.get_bind()
        insp = inspect(bind)
        if 'fiscal_years' in insp.get_table_names():
            existing_indexes = {idx['name'] for idx in insp.get_indexes('fiscal_years')}
            if 'ix_fiscal_years_title' in existing_indexes:
                op.drop_index(op.f('ix_fiscal_years_title'), table_name='fiscal_years')
    except Exception:
        pass

    conn = op.get_bind()
    if _table_exists(conn, 'person_bank_accounts') and _column_exists(conn, 'person_bank_accounts', 'person_id'):
        op.alter_column('person_bank_accounts', 'person_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='شناسه شخص',
               existing_nullable=False)

    if _table_exists(conn, 'persons'):
        if _column_exists(conn, 'persons', 'business_id'):
            op.alter_column('persons', 'business_id',
                   existing_type=mysql.INTEGER(),
                   comment=None,
                   existing_comment='شناسه کسب و کار',
                   existing_nullable=False)
        if _column_exists(conn, 'persons', 'code'):
            op.alter_column('persons', 'code',
                   existing_type=mysql.INTEGER(),
                   comment='کد یکتا در هر کسب و کار',
                   existing_nullable=True)
        if _column_exists(conn, 'persons', 'person_types'):
            op.alter_column('persons', 'person_types',
                   existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
                   comment='لیست انواع شخص به صورت JSON',
                   existing_nullable=True)
        if _column_exists(conn, 'persons', 'share_count'):
            op.alter_column('persons', 'share_count',
                   existing_type=mysql.INTEGER(),
                   comment='تعداد سهام (فقط برای سهامدار)',
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    if _table_exists(conn, 'persons') and _column_exists(conn, 'persons', 'share_count'):
        op.alter_column('persons', 'share_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='تعداد سهام (فقط برای سهامدار)',
               existing_nullable=True)
    if _table_exists(conn, 'persons') and _column_exists(conn, 'persons', 'person_types'):
        op.alter_column('persons', 'person_types',
               existing_type=mysql.TEXT(collation='utf8mb4_general_ci'),
               comment=None,
               existing_comment='لیست انواع شخص به صورت JSON',
               existing_nullable=True)
    if _table_exists(conn, 'persons') and _column_exists(conn, 'persons', 'code'):
        op.alter_column('persons', 'code',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='کد یکتا در هر کسب و کار',
               existing_nullable=True)
    if _table_exists(conn, 'persons') and _column_exists(conn, 'persons', 'business_id'):
        op.alter_column('persons', 'business_id',
               existing_type=mysql.INTEGER(),
               comment='شناسه کسب و کار',
               existing_nullable=False)
    if _table_exists(conn, 'person_bank_accounts') and _column_exists(conn, 'person_bank_accounts', 'person_id'):
        op.alter_column('person_bank_accounts', 'person_id',
               existing_type=mysql.INTEGER(),
               comment='شناسه شخص',
               existing_nullable=False)
    op.create_index(op.f('ix_fiscal_years_title'), 'fiscal_years', ['title'], unique=False)
    op.drop_table('file_verifications')
    op.drop_table('file_storage')
    op.drop_table('storage_configs')
    # ### end Alembic commands ###
