# noqa: D100
"""انواع رویداد قالب نوتیفیکیشن کسب‌وکار — یک منبع برای مهاجرت و اسکریپت seed."""

from __future__ import annotations

# متغیرهای مشترک فاکتور (ارسال دستی + دادهٔ ورک‌فلو / غنی‌سازی سند)
INVOICE_TEMPLATE_VARIABLES: list[dict[str, str]] = [
    {"key": "invoice_number", "type": "string", "description": "شماره فاکتور"},
    {"key": "invoice_code", "type": "string", "description": "کد سند فاکتور"},
    {"key": "customer_name", "type": "string", "description": "نام طرف حساب در سند"},
    {"key": "invoice_date", "type": "date", "description": "تاریخ فاکتور"},
    {"key": "amount", "type": "number", "description": "مبلغ کل (سناریوهای دستی یا معادل با total_amount)"},
    {"key": "total_amount", "type": "number", "description": "مبلغ کل از تریگر ورک‌فلو (invoice.created)"},
    {"key": "final_amount", "type": "number", "description": "مبلغ نهایی بعد از تخفیف و مالیات"},
    {"key": "tax_amount", "type": "number", "description": "جمع مالیات"},
    {"key": "discount_amount", "type": "number", "description": "جمع تخفیف"},
    {"key": "due_date", "type": "date", "description": "تاریخ سررسید"},
    {"key": "business_name", "type": "string", "description": "نام کسب‌وکار"},
    {"key": "business_phone", "type": "string", "description": "تلفن کسب‌وکار"},
]

# رویدادهای تکمیلی ورک‌فلو — مهاجرت جدا برای نصب‌هایی که قبلاً seed اولیه را داشتند
WORKFLOW_EXTENSION_EVENT_CODES: frozenset[str] = frozenset(
    {
        "document.created",
        "person.created",
        "crm.lead.created",
        "crm.deal.closed",
        "inventory.low",
        "check.due_date",
        "distribution.visit.completed",
    }
)

NOTIFICATION_EVENT_TYPES_ROWS: list[dict] = [
    {
        "code": "invoice.created",
        "name": "ثبت فاکتور (عمومی — ورک‌فلو)",
        "description": "با تریگر عمومی «invoice.created» در اتوماسیون؛ برای همه انواع فاکتور فعال می‌شود. برای فقط فروش یا فقط خرید، رویداد اختصاصی را انتخاب کنید.",
        "category": "sales",
        "available_variables": list(INVOICE_TEMPLATE_VARIABLES),
        "default_sms_template": "سلام {{ customer_name }} عزیز، فاکتور شماره {{ invoice_number }} به مبلغ {{ amount | format_currency }} برای شما ثبت شد. با تشکر، {{ business_name }}",
        "default_email_template": """سلام {{ customer_name }} عزیز،

فاکتور شماره {{ invoice_number }} به تاریخ {{ invoice_date | format_date }} برای شما ثبت شد.

مبلغ کل: {{ amount | format_currency }}
تاریخ سررسید: {{ due_date | format_date }}

با تشکر،
{{ business_name }}
تلفن: {{ business_phone }}""",
        "default_email_subject": "فاکتور جدید - {{ invoice_number }}",
        "is_active": True,
        "requires_approval": True,
    },
    {
        "code": "invoice.sales.created",
        "name": "ثبت فاکتور فروش",
        "description": "فقط هنگام ثبت فاکتور فروش (تریگر «invoice.sales.created» در ورک‌فلو).",
        "category": "sales",
        "available_variables": list(INVOICE_TEMPLATE_VARIABLES),
        "default_sms_template": "سلام {{ customer_name }} عزیز، فاکتور فروش {{ invoice_number }} به مبلغ {{ final_amount | format_currency }} ثبت شد. {{ business_name }}",
        "default_email_template": """سلام {{ customer_name }} عزیز،

فاکتور فروش {{ invoice_number }} به تاریخ {{ invoice_date | format_date }} ثبت شد.

مبلغ نهایی: {{ final_amount | format_currency }}

{{ business_name }} — {{ business_phone }}""",
        "default_email_subject": "فاکتور فروش جدید - {{ invoice_number }}",
        "is_active": True,
        "requires_approval": True,
    },
    {
        "code": "invoice.purchase.created",
        "name": "ثبت فاکتور خرید",
        "description": "فقط هنگام ثبت فاکتور خرید (تریگر «invoice.purchase.created»).",
        "category": "purchases",
        "available_variables": list(INVOICE_TEMPLATE_VARIABLES),
        "default_sms_template": "فاکتور خرید {{ invoice_number }} به مبلغ {{ final_amount | format_currency }} ثبت شد. طرف حساب: {{ customer_name }}. {{ business_name }}",
        "default_email_template": """فاکتور خرید {{ invoice_number }} — تاریخ {{ invoice_date | format_date }}

مبلغ نهایی: {{ final_amount | format_currency }}
طرف حساب: {{ customer_name }}

{{ business_name }}""",
        "default_email_subject": "فاکتور خرید - {{ invoice_number }}",
        "is_active": True,
        "requires_approval": True,
    },
    {
        "code": "receipt_payment.created",
        "name": "ثبت سند دریافت / پرداخت",
        "description": "هنگام ثبت سند دریافت یا پرداخت (تریگر «receipt_payment.created»).",
        "category": "financial",
        "available_variables": [
            {"key": "amount", "type": "number", "description": "مبلغ سند"},
            {"key": "payment_method", "type": "string", "description": "روش پرداخت (نقد، بانک، چک و …)"},
            {"key": "type", "type": "string", "description": "receipt یا payment"},
            {"key": "description", "type": "string", "description": "شرح سند"},
            {"key": "person_id", "type": "number", "description": "شناسه شخص در سند (در صورت وجود)"},
            {"key": "business_name", "type": "string", "description": "نام کسب‌وکار"},
            {"key": "business_phone", "type": "string", "description": "تلفن کسب‌وکار"},
        ],
        "default_sms_template": "سند {{ type }} به مبلغ {{ amount | format_currency }} ثبت شد. {{ business_name }}",
        "default_email_subject": "ثبت سند مالی — {{ business_name }}",
        "is_active": True,
        "requires_approval": True,
    },
    {
        "code": "crm.chat.message.received",
        "name": "پیام جدید در چت وب",
        "description": "وقتی بازدیدکننده پیامی در چت وب CRM ارسال می‌کند («crm.chat.message.received»).",
        "category": "crm",
        "available_variables": [
            {"key": "visitor_first_name", "type": "string", "description": "نام بازدیدکننده"},
            {"key": "visitor_last_name", "type": "string", "description": "نام خانوادگی"},
            {"key": "visitor_phone", "type": "string", "description": "تلفن بازدیدکننده"},
            {"key": "visitor_email", "type": "string", "description": "ایمیل"},
            {"key": "page_url", "type": "string", "description": "صفحه‌ای که چت از آن باز شده"},
            {"key": "conversation_status", "type": "string", "description": "وضعیت مکالمه"},
            {"key": "business_name", "type": "string", "description": "نام کسب‌وکار"},
            {"key": "business_phone", "type": "string", "description": "تلفن کسب‌وکار"},
        ],
        "default_sms_template": "پیام جدید چت وب از {{ visitor_phone }} — {{ page_url }} — {{ business_name }}",
        "default_email_subject": "پیام جدید چت وب — {{ business_name }}",
        "is_active": True,
        "requires_approval": True,
    },
    {
        "code": "document.created",
        "name": "ثبت سند (عمومی)",
        "description": "پس از ایجاد سند حسابداری (هزینه/درآمد، سند دستی، …) با تریگر «document.created»؛ داده از غنی‌سازی سند پر می‌شود.",
        "category": "documents",
        "available_variables": [
            {"key": "document_id", "type": "number", "description": "شناسه سند"},
            {"key": "document_type", "type": "string", "description": "نوع سند"},
            {"key": "description", "type": "string", "description": "شرح سند"},
            {"key": "total_amount", "type": "number", "description": "جمع بدهکار سطرها (مبلغ کل)"},
            {"key": "is_proforma", "type": "string", "description": "پیش‌فاکتور بودن (true/false)"},
            {"key": "person_id", "type": "number", "description": "شناسه طرف‌حساب در صورت وجود"},
            {"key": "fiscal_year_id", "type": "number", "description": "شناسه سال مالی"},
            {"key": "project_id", "type": "number", "description": "شناسه پروژه در صورت وجود"},
            {"key": "business_name", "type": "string", "description": "نام کسب‌وکار"},
            {"key": "business_phone", "type": "string", "description": "تلفن کسب‌وکار"},
        ],
        "default_sms_template": "سند {{ document_type }} ثبت شد (مبلغ {{ total_amount | format_currency }}). {{ business_name }}",
        "default_email_subject": "سند جدید — {{ business_name }}",
        "is_active": True,
        "requires_approval": True,
    },
    {
        "code": "person.created",
        "name": "ایجاد شخص جدید",
        "description": "با تریگر «person.created»؛ معمولاً فقط person_id و person_types در context است — نام را در ورک‌فلو با گره تکمیل داده اضافه کنید.",
        "category": "people",
        "available_variables": [
            {"key": "person_id", "type": "number", "description": "شناسه شخص جدید"},
            {"key": "person_types", "type": "string", "description": "انواع شخص (در ورک‌فلو به‌صورت داده ساختاریافته؛ در قالب متنی نمایش داده می‌شود)"},
            {"key": "person_name", "type": "string", "description": "نام نمایشی (در صورت افزودن در ورک‌فلو)"},
            {"key": "business_name", "type": "string", "description": "نام کسب‌وکار"},
            {"key": "business_phone", "type": "string", "description": "تلفن کسب‌وکار"},
        ],
        "default_sms_template": "شخص جدید در {{ business_name }} ثبت شد (شناسه {{ person_id }}).",
        "default_email_subject": "شخص جدید — {{ business_name }}",
        "is_active": True,
        "requires_approval": True,
    },
    {
        "code": "crm.lead.created",
        "name": "ایجاد سرنخ CRM",
        "description": "تریگر «crm.lead.created» هنگام ایجاد سرنخ؛ فیلدها از trigger_data و غنی‌سازی Lead.",
        "category": "crm",
        "available_variables": [
            {"key": "lead_id", "type": "number", "description": "شناسه سرنخ"},
            {"key": "name", "type": "string", "description": "نام سرنخ (همان name اولیه)"},
            {"key": "lead_code", "type": "string", "description": "کد سرنخ"},
            {"key": "stage_name", "type": "string", "description": "نام مرحله فعلی"},
            {"key": "stage_code", "type": "string", "description": "کد مرحله"},
            {"key": "source_code", "type": "string", "description": "کد منبع"},
            {"key": "company_name", "type": "string", "description": "نام شرکت"},
            {"key": "mobile", "type": "string", "description": "موبایل"},
            {"key": "email", "type": "string", "description": "ایمیل"},
            {"key": "person_name", "type": "string", "description": "نام شخص مرتبط"},
            {"key": "assigned_to_user_name", "type": "string", "description": "نام کاربر مسئول"},
            {"key": "process_definition_name", "type": "string", "description": "نام فانل/فرایند"},
            {"key": "next_follow_up_at", "type": "date", "description": "زمان پیگیری بعدی (ISO)"},
            {"key": "business_name", "type": "string", "description": "نام کسب‌وکار"},
            {"key": "business_phone", "type": "string", "description": "تلفن کسب‌وکار"},
        ],
        "default_sms_template": "سرنخ جدید {{ name }} — مرحله {{ stage_name }}. {{ business_name }}",
        "default_email_subject": "سرنخ CRM جدید — {{ lead_code }}",
        "is_active": True,
        "requires_approval": True,
    },
    {
        "code": "crm.deal.closed",
        "name": "بستن معامله CRM",
        "description": "تریگر «crm.deal.closed»؛ شامل وضعیت برد/باخت و غنی‌سازی فرصت فروش.",
        "category": "crm",
        "available_variables": [
            {"key": "deal_id", "type": "number", "description": "شناسه فرصت"},
            {"key": "is_win", "type": "string", "description": "معامله موفق (true/false)"},
            {"key": "is_lost", "type": "string", "description": "از دست رفته (true/false)"},
            {"key": "amount", "type": "number", "description": "مبلغ در لحظه بستن"},
            {"key": "title", "type": "string", "description": "عنوان فرصت"},
            {"key": "deal_code", "type": "string", "description": "کد فرصت"},
            {"key": "stage_name", "type": "string", "description": "نام مرحله"},
            {"key": "person_name", "type": "string", "description": "نام مشتری مرتبط"},
            {"key": "probability_percent", "type": "number", "description": "درصد احتمال"},
            {"key": "document_id", "type": "number", "description": "شناسه سند مرتبط در صورت وجود"},
            {"key": "business_name", "type": "string", "description": "نام کسب‌وکار"},
            {"key": "business_phone", "type": "string", "description": "تلفن کسب‌وکار"},
        ],
        "default_sms_template": "معامله {{ title }} بسته شد (برنده: {{ is_win }}). مبلغ {{ amount | format_currency }}. {{ business_name }}",
        "default_email_subject": "بستن معامله — {{ deal_code }}",
        "is_active": True,
        "requires_approval": True,
    },
    {
        "code": "inventory.low",
        "name": "هشدار کمبود موجودی",
        "description": "وقتی موجودی کالا به نقطه سفارش (reorder) یا پایین‌تر برسد — «inventory.low».",
        "category": "warehouse",
        "available_variables": [
            {"key": "product_id", "type": "number", "description": "شناسه کالا"},
            {"key": "current_quantity", "type": "number", "description": "موجودی فعلی"},
            {"key": "min_quantity", "type": "number", "description": "حداقل / نقطه سفارش"},
            {"key": "warehouse_id", "type": "number", "description": "شناسه انبار در صورت وجود"},
            {"key": "business_name", "type": "string", "description": "نام کسب‌وکار"},
            {"key": "business_phone", "type": "string", "description": "تلفن کسب‌وکار"},
        ],
        "default_sms_template": "هشدار موجودی: کالا {{ product_id }} به {{ current_quantity | format_number }} رسید (حد {{ min_quantity | format_number }}). {{ business_name }}",
        "default_email_subject": "کمبود موجودی — {{ business_name }}",
        "is_active": True,
        "requires_approval": True,
    },
    {
        "code": "check.due_date",
        "name": "سررسید چک",
        "description": "یادآوری/اجرای ورک‌فلو برای چک نزدیک سررسید — «check.due_date».",
        "category": "financial",
        "available_variables": [
            {"key": "check_id", "type": "number", "description": "شناسه چک"},
            {"key": "check_number", "type": "string", "description": "شماره چک"},
            {"key": "amount", "type": "number", "description": "مبلغ چک"},
            {"key": "check_type", "type": "string", "description": "received یا paid"},
            {"key": "due_date", "type": "date", "description": "تاریخ سررسید (ISO)"},
            {"key": "days_until_due", "type": "number", "description": "تعداد روز تا سررسید (منفی یعنی گذشته)"},
            {"key": "person_id", "type": "number", "description": "شناسه طرف چک"},
            {"key": "business_name", "type": "string", "description": "نام کسب‌وکار"},
            {"key": "business_phone", "type": "string", "description": "تلفن کسب‌وکار"},
        ],
        "default_sms_template": "چک {{ check_number }} به مبلغ {{ amount | format_currency }} — {{ days_until_due }} روز تا سررسید. {{ business_name }}",
        "default_email_subject": "سررسید چک {{ check_number }}",
        "is_active": True,
        "requires_approval": True,
    },
    {
        "code": "distribution.visit.completed",
        "name": "تکمیل ویزیت میدانی (پخش)",
        "description": "پس از تکمیل ویزیت در افزونه پخش مویرگی — «distribution.visit.completed».",
        "category": "distribution",
        "available_variables": [
            {"key": "visit_id", "type": "number", "description": "شناسه ویزیت"},
            {"key": "person_id", "type": "number", "description": "شناسه مشتری/مکان ویزیت"},
            {"key": "user_id", "type": "number", "description": "شناسه ویزیتور"},
            {"key": "route_id", "type": "number", "description": "شناسه مسیر"},
            {"key": "status", "type": "string", "description": "وضعیت ویزیت"},
            {"key": "outcome", "type": "string", "description": "نتیجه ویزیت"},
            {"key": "document_id", "type": "number", "description": "سند ایجادشده در صورت وجود"},
            {"key": "deal_id", "type": "number", "description": "فرصت فروش مرتبط"},
            {"key": "started_at", "type": "date", "description": "شروع ویزیت (ISO)"},
            {"key": "ended_at", "type": "date", "description": "پایان ویزیت (ISO)"},
            {"key": "business_name", "type": "string", "description": "نام کسب‌وکار"},
            {"key": "business_phone", "type": "string", "description": "تلفن کسب‌وکار"},
        ],
        "default_sms_template": "ویزیت {{ visit_id }} برای مشتری {{ person_id }} تکمیل شد — {{ outcome }}. {{ business_name }}",
        "default_email_subject": "ویزیت میدانی تکمیل شد — {{ business_name }}",
        "is_active": True,
        "requires_approval": True,
    },
    {
        "code": "repair_shop.received",
        "name": "دریافت کالا در تعمیرگاه",
        "description": "هنگامی که کالای مشتری برای تعمیر دریافت می‌شود",
        "category": "repair_shop",
        "available_variables": [
            {"key": "repair_code", "type": "string", "description": "کد رسید تعمیر"},
            {"key": "customer_name", "type": "string", "description": "نام مشتری"},
            {"key": "product_name", "type": "string", "description": "نام کالا"},
            {"key": "received_date", "type": "date", "description": "تاریخ دریافت"},
            {"key": "estimated_delivery", "type": "date", "description": "تاریخ تحویل تقریبی"},
            {"key": "business_name", "type": "string", "description": "نام تعمیرگاه"},
            {"key": "business_phone", "type": "string", "description": "تلفن تعمیرگاه"},
        ],
        "default_sms_template": "سلام {{ customer_name }} عزیز، {{ product_name }} شما با کد {{ repair_code }} دریافت شد. تاریخ تحویل تقریبی: {{ estimated_delivery | format_date }}. {{ business_name }}",
        "default_email_subject": "دریافت کالا - {{ repair_code }}",
        "is_active": True,
        "requires_approval": True,
    },
    {
        "code": "repair_shop.ready",
        "name": "آماده تحویل از تعمیرگاه",
        "description": "هنگامی که کالای تعمیر شده آماده تحویل است",
        "category": "repair_shop",
        "available_variables": [
            {"key": "repair_code", "type": "string", "description": "کد رسید تعمیر"},
            {"key": "customer_name", "type": "string", "description": "نام مشتری"},
            {"key": "product_name", "type": "string", "description": "نام کالا"},
            {"key": "final_cost", "type": "number", "description": "هزینه نهایی"},
            {"key": "status", "type": "string", "description": "وضعیت (تعمیر موفق/غیرقابل تعمیر)"},
            {"key": "business_name", "type": "string", "description": "نام تعمیرگاه"},
            {"key": "business_phone", "type": "string", "description": "تلفن تعمیرگاه"},
        ],
        "default_sms_template": "سلام {{ customer_name }}، {{ product_name }} شما (کد {{ repair_code }}) آماده تحویل است. هزینه: {{ final_cost | format_currency }}. {{ business_name }} - {{ business_phone }}",
        "default_email_subject": "کالای شما آماده تحویل است - {{ repair_code }}",
        "is_active": True,
        "requires_approval": True,
    },
    {
        "code": "payment.received",
        "name": "دریافت پرداخت",
        "description": "هنگامی که پرداختی از مشتری دریافت می‌شود",
        "category": "financial",
        "available_variables": [
            {"key": "receipt_number", "type": "string", "description": "شماره رسید"},
            {"key": "customer_name", "type": "string", "description": "نام پرداخت‌کننده"},
            {"key": "amount", "type": "number", "description": "مبلغ دریافتی"},
            {"key": "payment_date", "type": "date", "description": "تاریخ پرداخت"},
            {"key": "payment_method", "type": "string", "description": "روش پرداخت"},
            {"key": "remaining_balance", "type": "number", "description": "مانده حساب"},
            {"key": "business_name", "type": "string", "description": "نام کسب‌وکار"},
        ],
        "default_sms_template": "سلام {{ customer_name }}، پرداخت شما به مبلغ {{ amount | format_currency }} با موفقیت دریافت شد. رسید: {{ receipt_number }}. با تشکر، {{ business_name }}",
        "default_email_subject": "رسید پرداخت - {{ receipt_number }}",
        "is_active": True,
        "requires_approval": True,
    },
    {
        "code": "payment.reminder",
        "name": "یادآوری پرداخت",
        "description": "یادآوری سررسید پرداخت به مشتری",
        "category": "financial",
        "available_variables": [
            {"key": "customer_name", "type": "string", "description": "نام مشتری"},
            {"key": "invoice_number", "type": "string", "description": "شماره فاکتور"},
            {"key": "amount", "type": "number", "description": "مبلغ بدهی"},
            {"key": "due_date", "type": "date", "description": "تاریخ سررسید"},
            {"key": "days_overdue", "type": "number", "description": "تعداد روز تأخیر"},
            {"key": "business_name", "type": "string", "description": "نام کسب‌وکار"},
            {"key": "business_phone", "type": "string", "description": "تلفن کسب‌وکار"},
        ],
        "default_sms_template": "سلام {{ customer_name }}، یادآوری: فاکتور {{ invoice_number }} به مبلغ {{ amount | format_currency }} در تاریخ {{ due_date | format_date }} سررسید دارد. {{ business_name }}",
        "default_email_subject": "یادآوری سررسید پرداخت - {{ invoice_number }}",
        "is_active": True,
        "requires_approval": True,
    },
    {
        "code": "order.shipped",
        "name": "ارسال سفارش",
        "description": "هنگامی که سفارش مشتری ارسال می‌شود",
        "category": "sales",
        "available_variables": [
            {"key": "order_number", "type": "string", "description": "شماره سفارش"},
            {"key": "customer_name", "type": "string", "description": "نام مشتری"},
            {"key": "tracking_code", "type": "string", "description": "کد رهگیری"},
            {"key": "courier_name", "type": "string", "description": "نام پیک/پست"},
            {"key": "estimated_delivery", "type": "date", "description": "تاریخ تحویل تقریبی"},
            {"key": "business_name", "type": "string", "description": "نام کسب‌وکار"},
        ],
        "default_sms_template": "سلام {{ customer_name }}، سفارش شما ({{ order_number }}) ارسال شد. کد رهگیری: {{ tracking_code }}. تحویل تقریبی: {{ estimated_delivery | format_date }}. {{ business_name }}",
        "default_email_subject": "سفارش شما ارسال شد - {{ order_number }}",
        "is_active": True,
        "requires_approval": True,
    },
    {
        "code": "warranty.expires_soon",
        "name": "اتمام گارانتی",
        "description": "یادآوری اتمام گارانتی محصول",
        "category": "warranty",
        "available_variables": [
            {"key": "customer_name", "type": "string", "description": "نام مشتری"},
            {"key": "product_name", "type": "string", "description": "نام محصول"},
            {"key": "warranty_code", "type": "string", "description": "کد گارانتی"},
            {"key": "expiry_date", "type": "date", "description": "تاریخ اتمام"},
            {"key": "days_remaining", "type": "number", "description": "روزهای باقی‌مانده"},
            {"key": "business_name", "type": "string", "description": "نام کسب‌وکار"},
            {"key": "business_phone", "type": "string", "description": "تلفن کسب‌وکار"},
        ],
        "default_sms_template": "سلام {{ customer_name }}، گارانتی {{ product_name }} شما (کد {{ warranty_code }}) در تاریخ {{ expiry_date | format_date }} به پایان می‌رسد. {{ business_name }}",
        "default_email_subject": "یادآوری اتمام گارانتی - {{ product_name }}",
        "is_active": True,
        "requires_approval": True,
    },
    {
        "code": "person_share_link.sms",
        "name": "ارسال لینک کارت حساب به مشتری",
        "description": "ارسال لینک مشاهده کارت حساب (و در صورت تنظیم، فاکتورها) به مشتری از طریق پیامک",
        "category": "people",
        "available_variables": [
            {"key": "share_link", "type": "string", "description": "لینک کوتاه کارت حساب"},
            {"key": "customer_name", "type": "string", "description": "نام مشتری"},
            {"key": "customer_mobile", "type": "string", "description": "شماره موبایل مشتری"},
            {"key": "business_name", "type": "string", "description": "نام کسب‌وکار"},
            {"key": "business_phone", "type": "string", "description": "تلفن کسب‌وکار"},
        ],
        "default_sms_template": "سلام {{ customer_name }}، لینک کارت حساب شما: {{ share_link }} — {{ business_name }}",
        "default_email_subject": "لینک کارت حساب — {{ business_name }}",
        "is_active": True,
        "requires_approval": True,
    },
]
